Repository Tama-rb/shoukaigame, pull requests merged in 2019-08, with the labels that each got.

#21 Security Alertが出ていたライブラリのアップデート
  yarn.lock
Labels: その他 :smirk_cat:, レビュー依頼 :pray:

#26 Rails5.2にアップデートして不要になったCSRFの記述を削除
  app/controllers/application_controller.rb
Labels: サーバーサイド, レビュー依頼 :pray:

#27 Clean up controllers
  app/controllers/conjunctions_controller.rb
  app/controllers/homes_controller.rb
  app/controllers/questions_controller.rb
  app/controllers/themes_controller.rb
Labels: サーバーサイド, レビュー完了 :rocket:

#28 RuboCopとCircleCIのセットアップ
  .circleci/config.yml
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/questions_controller.rb
  app/controllers/conjunctions_controller.rb
  app/controllers/questions_controller.rb
  app/controllers/themes_controller.rb
  app/models/question.rb
  config/cors.rb
  config/routes.rb
  db/migrate/20181028092023_change_column_name_to_some_tables.rb
  test/test_helper.rb
Labels: その他 :smirk_cat:, サーバーサイド, レビュー完了 :rocket:

#30 フォームにデバッグ表示用の要素が混在していたので削除した
  app/javascript/new_item.vue
Labels: フロントエンド, レビュー依頼 :pray:

#31 RSpecをCircleCI上で動くようにした
  .circleci/config.yml
  .rspec
  Gemfile
  Gemfile.lock
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: その他 :smirk_cat:, レビュー依頼 :pray:

#33 開発環境をDocker化した
  Dockerfile
  config/database.yml
  docker-compose.yml
Labels: その他 :smirk_cat:, レビュー完了 :rocket:

#34 RSpecのモデルスペック追加および環境設定
  Gemfile
  Gemfile.lock
  bin/rspec
  spec/factories/questions.rb
  spec/models/question_spec.rb
  spec/rails_helper.rb
  test/application_system_test_case.rb
  test/controllers/.keep
  test/controllers/conjunctions_controller_test.rb
  test/controllers/homes_controller_test.rb
  test/controllers/questions_controller_test.rb
  test/controllers/themes_controller_test.rb
  test/fixtures/.keep
  test/fixtures/conjunctions.yml
  test/fixtures/files/.keep
  test/fixtures/questions.yml
  test/fixtures/themes.yml
  test/helpers/.keep
  test/integration/.keep
  test/mailers/.keep
  test/models/.keep
  test/models/conjunction_test.rb
  test/models/question_test.rb
  test/models/theme_test.rb
  test/system/.keep
  test/test_helper.rb
Labels: その他 :smirk_cat:, サーバーサイド, レビュー中 :speech_balloon:

#37 RSpecがCI上で動かない設定になっていたので修正した
  .circleci/config.yml
  config/database.yml
Labels: その他 :smirk_cat:, バグ :bug:, レビュー依頼 :pray:

#36 Controllerの記法の修正
  app/controllers/conjunctions_controller.rb
  app/controllers/questions_controller.rb
  app/controllers/themes_controller.rb
Labels: サーバーサイド, レビュー完了 :rocket:

#38 全件からランダムに1件レコードを取得するメソッドの改善
  app/controllers/conjunctions_controller.rb
  app/controllers/questions_controller.rb
  app/controllers/themes_controller.rb
  app/models/concerns/select_a_word_at_random.rb
  app/models/concerns/theme_selector.rb
  app/models/conjunction.rb
  app/models/question.rb
  app/models/theme.rb
Labels: サーバーサイド, レビュー中 :speech_balloon:

#39 使われていないファイル群の削除
  app/controllers/conjunctions_controller.rb
  app/controllers/questions_controller.rb
  app/controllers/themes_controller.rb
  app/models/concerns/theme_selector.rb
  app/models/conjunction.rb
  app/models/question.rb
  app/models/theme.rb
  app/views/conjunctions/_form.html.erb
  app/views/conjunctions/index.html.erb
  app/views/conjunctions/result.html.erb
  app/views/homes/index.html.erb
  app/views/layouts/mailer.html.erb
  app/views/layouts/mailer.text.erb
  app/views/questions/_form.html.erb
  app/views/questions/index.html.erb
  app/views/questions/result.html.erb
  app/views/themes/_form.html.erb
  app/views/themes/index.html.erb
  app/views/themes/result.html.erb
Labels: サーバーサイド, レビュー完了 :rocket:
